### ISSUE TITLE
Unable to access CID outside of browsers

### ISSUE THREAD

**Issue by expede** [fission-suite/ipfs-user-settings#15]
# Summary

## Problem

I am unable to reuse the CID anywhere other than in the browser.

### Impact

A premise of this demo app is that the settings data is portable to other machines, websites, and so on.

### Analysis

I'm guessing that the browser-local `js-ipfs` isn't getting bootstrapped with any of the common gateways.

## Solution

Attempt bootstrapping the broswer `js-ipfs` to well-known, active peer hubs, thereby announcing its presence as a place to look for files. Pinning a file to `hostless.dev` may also work in a less general case, but if it can't find the CID, that isn't going to work.

# Detail

**Describe the bug**

Webpage CIDs unable to be found on gateways

**To Reproduce**

1. Open the application
2. Fill out some settings
3. Press the `Save` button
4. Copy the new CID at the top of the page
5. Navigate to `ipfs.io/ipfs/<copied CID>`
6. [Gateway times out]

**Expected behavior**

6. Gateway returns the JSON file describing your settings

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser: Firefox Developer Edition 
 - Version: 69.0b13

**Comment by dholms** [comment]
Pins on save now :+1:
